FROM python:3.11-slim

# Set the working directory in the container
WORKDIR /app

# Avoid cache purge by adding requirements first
ADD ./requirements.txt ./requirements.txt

RUN pip install -r requirements.txt

# Add the rest of the files
COPY . /app
WORKDIR /app
